// This file is automatically generated from CSSProperties.json by the process-css-properties.py script. Do not edit it.

#pragma once

#ifndef USED_STYLE_PROPERTIES_GETTERS_INLINES_INCLUDE_TRAP
#error "Please do not include this file anywhere except from UsedStyle+GettersInlines.h."
#endif

#include <WebCore/RenderElement.h>
#include <WebCore/StyleComputedStyle+GettersInlines.h>

namespace WebCore {

inline Style::Number<> UsedStyleProperties::testRenderStyleStorageOneLevelValue() const
{
    return computedStyle().testRenderStyleStorageOneLevelValue();
}

} // namespace WebCore

