// This file is automatically generated from CSSProperties.json by the process-css-properties.py script. Do not edit it.

#include "config.h"
#include "UsedStyleProperties.h"

#include <WebCore/StylePrimitiveNumericTypes+Evaluation.h>
#include <WebCore/UsedStyle+GettersInlines.h>

namespace WebCore {

} // namespace WebCore

